/*
 * This source file was generated by the Gradle 'init' task
 */
package org.authentication;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        System.out.println("Authentication app running...");
    }
    public String getGreeting() {
        return "Hello!";
    }

}
